### ISSUE TITLE
interfere of docker-clean and k8s-clean tasks?

### ISSUE THREAD

**Issue by unacao** [onfido/k8s-cleanup#9]
With the last line of CMD in the dockerfile running "docker-clean.sh", won't the launch of a k8s-clean cronjob pod also trigger the running of docker-clean at the same time?

**Comment by adrianchifor** [comment]
Nope, the CMD is overwritten in the k8s manifest

**Comment by unacao** [comment]
do you mean this line will override the CMD? command: ["/bin/bash", "/bin/k8s-clean.sh"]

**Comment by adrianchifor** [comment]
Yes
